export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST'
export const FETCH_POST_SUCCESS = 'FETCH_POST_REQUEST'
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE'
export const ADD_COMMENT = 'ADD_COMMENT'